# Generated by Django 3.1.7 on 2021-04-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='about',
        ),
    ]
