# Generated by Django 3.1.7 on 2021-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210401_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
