# Generated by Django 3.1.7 on 2021-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210426_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Finland', max_length=100),
            preserve_default=False,
        ),
    ]
